#include "Slimmer.h"
#include "TFile.h"
#include "TTree.h"
#include "TROOT.h"
#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include "TString.h"
using namespace std;

void Slimmer(TString InputCfAName, TString output_filename)
{
    
  TChain * chainA = new TChain("/configurableAnalysis/eventA");   
  TChain * chainB = new TChain("/configurableAnalysis/eventB");    
  chainA->Add(InputCfAName);
  chainB->Add(InputCfAName);

  InitializeA(chainA);
  InitializeB(chainB);
  
  chainA->SetBranchStatus("*",0);
  chainB->SetBranchStatus("*",0);

  chainA->SetBranchStatus("els_conversion_dist",1);
  chainA->SetBranchStatus("els_conversion_dcot",1);
  chainA->SetBranchStatus("PU_TrueNumInteractions",1);
  chainA->SetBranchStatus("rho_kt6PFJetsForIsolation2011",1);
  chainA->SetBranchStatus("els_PFphotonIsoR03",1);
  chainA->SetBranchStatus("els_PFneutralHadronIsoR03",1);
  chainA->SetBranchStatus("els_PFchargedHadronIsoR03",1);
  chainA->SetBranchStatus("els_hasMatchedConversion",1);

  chainB->SetBranchStatus("mus_charge",1);
  chainB->SetBranchStatus("mus_pt",1);
  chainB->SetBranchStatus("mus_eta",1);
  chainB->SetBranchStatus("mus_et",1);
  chainB->SetBranchStatus("mus_phi",1);
  chainB->SetBranchStatus("mus_px",1);
  chainB->SetBranchStatus("mus_py",1);
  chainB->SetBranchStatus("mus_pz",1);
  chainB->SetBranchStatus("mus_tk_chi2",1);
  chainB->SetBranchStatus("mus_tk_ndof",1);
  chainB->SetBranchStatus("mus_tk_numvalhits",1);
  chainB->SetBranchStatus("mus_tk_numvalPixelhits",1);
  chainB->SetBranchStatus("mus_tk_px",1);
  chainB->SetBranchStatus("mus_tk_py",1);
  chainB->SetBranchStatus("mus_tk_pz",1);
  chainB->SetBranchStatus("mus_tk_pt",1);
  chainB->SetBranchStatus("mus_tk_ptErr",1);
  chainB->SetBranchStatus("mus_tk_numpixelWthMeasr",1);
  chainB->SetBranchStatus("mus_tk_vx",1);
  chainB->SetBranchStatus("mus_tk_vy",1);
  chainB->SetBranchStatus("mus_tk_vz",1);
  chainB->SetBranchStatus("mus_tk_d0dum",1);
  chainB->SetBranchStatus("mus_tk_phi",1);
  chainB->SetBranchStatus("mus_cm_pt",1);
  chainB->SetBranchStatus("mus_cm_ptErr",1);
  chainB->SetBranchStatus("mus_cm_chi2",1);
  chainB->SetBranchStatus("mus_cm_ndof",1);
  chainB->SetBranchStatus("mus_stamu_pt",1);
  chainB->SetBranchStatus("mus_stamu_ptErr",1);
  chainB->SetBranchStatus("mus_tIso",1);
  chainB->SetBranchStatus("mus_cIso",1);
  chainB->SetBranchStatus("mus_energy",1);
  chainB->SetBranchStatus("mus_ecalIso",1);
  chainB->SetBranchStatus("mus_hcalIso",1);
  chainB->SetBranchStatus("mus_ecalvetoDep",1);
  chainB->SetBranchStatus("mus_hcalvetoDep",1);
  chainB->SetBranchStatus("mus_id_GlobalMuonPromptTight",1);
  chainB->SetBranchStatus("mus_id_AllTrackerMuons",1);
  chainB->SetBranchStatus("mus_id_AllGlobalMuons",1);
  chainB->SetBranchStatus("mus_isTrackerMuon",1);
  chainB->SetBranchStatus("mus_isGlobalMuon",1);
  chainB->SetBranchStatus("mus_num_matches",1);
  chainB->SetBranchStatus("mus_isPFMuon",1);
  chainB->SetBranchStatus("mus_numberOfMatchedStations",1);
  chainB->SetBranchStatus("mus_pfIsolationR03_sumChargedHadronPt",1);
  chainB->SetBranchStatus("mus_pfIsolationR03_sumChargedParticlePt",1);
  chainB->SetBranchStatus("mus_pfIsolationR03_sumNeutralHadronEt",1);
  chainB->SetBranchStatus("mus_pfIsolationR03_sumNeutralHadronEtHighThreshold",1);
  chainB->SetBranchStatus("mus_pfIsolationR03_sumPhotonEt",1);
  chainB->SetBranchStatus("mus_pfIsolationR03_sumPhotonEtHighThreshold",1);
  chainB->SetBranchStatus("mus_pfIsolationR03_sumPUPt",1);
  chainB->SetBranchStatus("mus_pfIsolationR04_sumChargedHadronPt",1);
  chainB->SetBranchStatus("mus_pfIsolationR04_sumChargedParticlePt",1);
  chainB->SetBranchStatus("mus_pfIsolationR04_sumNeutralHadronEt",1);
  chainB->SetBranchStatus("mus_pfIsolationR04_sumNeutralHadronEtHighThreshold",1);
  chainB->SetBranchStatus("mus_pfIsolationR04_sumPhotonEt",1);
  chainB->SetBranchStatus("mus_pfIsolationR04_sumPhotonEtHighThreshold",1);
  chainB->SetBranchStatus("mus_pfIsolationR04_sumPUPt",1);
  chainB->SetBranchStatus("mus_dB",1);

  chainB->SetBranchStatus("pfcand_pdgId",1);
  chainB->SetBranchStatus("pfcand_particleId",1);
  chainB->SetBranchStatus("pfcand_pt",1);
  chainB->SetBranchStatus("pfcand_pz",1);
  chainB->SetBranchStatus("pfcand_px",1);
  chainB->SetBranchStatus("pfcand_py",1);
  chainB->SetBranchStatus("pfcand_eta",1);
  chainB->SetBranchStatus("pfcand_phi",1);
  chainB->SetBranchStatus("pfcand_theta",1);
  chainB->SetBranchStatus("pfcand_energy",1);
  chainB->SetBranchStatus("pfcand_charge",1);

  chainB->SetBranchStatus("pf_mus_pt",1);
  chainB->SetBranchStatus("pf_mus_eta",1);
  chainB->SetBranchStatus("pf_mus_et",1);
  chainB->SetBranchStatus("pf_mus_tk_chi2",1);
  chainB->SetBranchStatus("pf_mus_tk_ndof",1);
  chainB->SetBranchStatus("pf_mus_tk_numvalhits",1);
  chainB->SetBranchStatus("pf_mus_tk_numvalPixelhits",1);
  chainB->SetBranchStatus("pf_mus_tk_pt",1);
  chainB->SetBranchStatus("pf_mus_tk_ptErr",1);
  chainB->SetBranchStatus("pf_mus_cm_pt",1);
  chainB->SetBranchStatus("pf_mus_cm_ptErr",1);
  chainB->SetBranchStatus("pf_mus_cm_chi2",1);
  chainB->SetBranchStatus("pf_mus_cm_ndof",1);
  chainB->SetBranchStatus("pf_mus_stamu_pt",1);
  chainB->SetBranchStatus("pf_mus_stamu_ptErr",1);
  chainB->SetBranchStatus("pf_mus_tIso",1);
  chainB->SetBranchStatus("pf_mus_cIso",1);
  chainB->SetBranchStatus("pf_mus_energy",1);
  chainB->SetBranchStatus("pf_mus_ecalIso",1);
  chainB->SetBranchStatus("pf_mus_hcalIso",1);
  chainB->SetBranchStatus("pf_mus_tk_d0dum",1);
  chainB->SetBranchStatus("pf_mus_tk_phi",1);
  chainB->SetBranchStatus("pf_mus_phi",1);
  chainB->SetBranchStatus("pf_mus_px",1);
  chainB->SetBranchStatus("pf_mus_py",1);
  chainB->SetBranchStatus("pf_mus_pz",1);
  chainB->SetBranchStatus("pf_mus_id_GlobalMuonPromptTight",1);
  chainB->SetBranchStatus("pf_mus_charge",1);
  chainB->SetBranchStatus("pf_mus_num_matches",1);
  chainB->SetBranchStatus("pf_mus_tk_numpixelWthMeasr",1);
  chainB->SetBranchStatus("pf_mus_tk_vz",1);
  chainB->SetBranchStatus("mus_tk_LayersWithMeasurement",1);
  chainB->SetBranchStatus("pf_mus_isTrackerMuon",1);
  chainB->SetBranchStatus("pf_mus_isGlobalMuon",1);
  chainB->SetBranchStatus("pf_mus_chargedHadronIso",1);
  chainB->SetBranchStatus("pf_mus_neutralHadronIso",1);
  chainB->SetBranchStatus("pf_mus_photonIso",1);

  chainB->SetBranchStatus("els_pt",1);
  chainB->SetBranchStatus("els_ptError",1);
  chainB->SetBranchStatus("els_n_inner_layer");
  chainB->SetBranchStatus("els_px",1);
  chainB->SetBranchStatus("els_py",1);
  chainB->SetBranchStatus("els_pz",1);
  chainB->SetBranchStatus("els_et",1);
  chainB->SetBranchStatus("els_eta",1);
  chainB->SetBranchStatus("els_phi",1);
  chainB->SetBranchStatus("els_charge",1);
  chainB->SetBranchStatus("els_isEB",1);
  chainB->SetBranchStatus("els_isEE",1);
  chainB->SetBranchStatus("els_simpleEleId70relIso",1);
  chainB->SetBranchStatus("els_simpleEleId70cIso",1);
  chainB->SetBranchStatus("els_simpleEleId80cIso",1);
  chainB->SetBranchStatus("els_simpleEleId80relIso",1);
  chainB->SetBranchStatus("els_simpleEleId85cIso",1);
  chainB->SetBranchStatus("els_simpleEleId85relIso",1);
  chainB->SetBranchStatus("els_simpleEleId90cIso",1);
  chainB->SetBranchStatus("els_simpleEleId90relIso",1);
  chainB->SetBranchStatus("els_simpleEleId95cIso",1);
  chainB->SetBranchStatus("els_simpleEleId95relIso",1);
  chainB->SetBranchStatus("els_tIso",1);
  chainB->SetBranchStatus("els_cIso",1);
  chainB->SetBranchStatus("els_hcalIso",1);
  chainB->SetBranchStatus("els_ecalIso",1);
  chainB->SetBranchStatus("els_d0dum",1);
  chainB->SetBranchStatus("els_tk_phi",1);
  chainB->SetBranchStatus("els_tk_pt",1);
  chainB->SetBranchStatus("els_tk_pz",1);
  chainB->SetBranchStatus("els_robustTightId",1);
  chainB->SetBranchStatus("els_dr03EcalRecHitSumEt",1);
  chainB->SetBranchStatus("els_dr03TkSumPt",1);
  chainB->SetBranchStatus("els_dr03HcalTowerSumEt",1);
  chainB->SetBranchStatus("els_sigmaIEtaIEta",1);
  chainB->SetBranchStatus("els_dPhiIn",1);
  chainB->SetBranchStatus("els_dEtaIn",1);
  chainB->SetBranchStatus("els_dPhiOut",1);
  chainB->SetBranchStatus("els_dEtaOut",1);
  chainB->SetBranchStatus("els_scEta",1);
  chainB->SetBranchStatus("els_hadOverEm",1);
  chainB->SetBranchStatus("els_isEB",1);
  chainB->SetBranchStatus("els_isEE",1);
  chainB->SetBranchStatus("els_energy",1);
  chainB->SetBranchStatus("els_scEnergy",1);
  chainB->SetBranchStatus("els_scE2x5Max",1);
  chainB->SetBranchStatus("els_scE5x5",1);
  chainB->SetBranchStatus("els_scE1x5",1);
  chainB->SetBranchStatus("els_dr03HcalDepth1TowerSumEt",1);
  chainB->SetBranchStatus("els_dr03HcalDepth2TowerSumEt",1);
  chainB->SetBranchStatus("els_eOverPIn",1);
  chainB->SetBranchStatus("els_numlosthits",1);
  chainB->SetBranchStatus("els_vx",1);
  chainB->SetBranchStatus("els_vy",1);
  chainB->SetBranchStatus("els_vz",1);
  chainB->SetBranchStatus("els_caloEnergy",1);

  chainB->SetBranchStatus("pf_els_pt",1);
  chainB->SetBranchStatus("pf_els_ptError",1);
  chainB->SetBranchStatus("pf_els_n_inner_layer");
  chainB->SetBranchStatus("pf_els_px",1);
  chainB->SetBranchStatus("pf_els_py",1);
  chainB->SetBranchStatus("pf_els_pz",1);
  chainB->SetBranchStatus("pf_els_et",1);
  chainB->SetBranchStatus("pf_els_eta",1);
  chainB->SetBranchStatus("pf_els_phi",1);
  chainB->SetBranchStatus("pf_els_charge",1);
  chainB->SetBranchStatus("pf_els_isEB",1);
  chainB->SetBranchStatus("pf_els_isEE",1);
  chainB->SetBranchStatus("pf_els_simpleEleId70relIso",1);
  chainB->SetBranchStatus("pf_els_simpleEleId70cIso",1);
  chainB->SetBranchStatus("pf_els_simpleEleId80cIso",1);
  chainB->SetBranchStatus("pf_els_simpleEleId80relIso",1);
  chainB->SetBranchStatus("pf_els_simpleEleId85cIso",1);
  chainB->SetBranchStatus("pf_els_simpleEleId85relIso",1);
  chainB->SetBranchStatus("pf_els_simpleEleId90cIso",1);
  chainB->SetBranchStatus("pf_els_simpleEleId90relIso",1);
  chainB->SetBranchStatus("pf_els_simpleEleId95cIso",1);
  chainB->SetBranchStatus("pf_els_simpleEleId95relIso",1);
  chainB->SetBranchStatus("pf_els_tIso",1);
  chainB->SetBranchStatus("pf_els_cIso",1);
  chainB->SetBranchStatus("pf_els_hcalIso",1);
  chainB->SetBranchStatus("pf_els_ecalIso",1);
  chainB->SetBranchStatus("pf_els_d0dum",1);
  chainB->SetBranchStatus("pf_els_tk_phi",1);
  chainB->SetBranchStatus("pf_els_robustTightId",1);
  chainB->SetBranchStatus("pf_els_dr03EcalRecHitSumEt",1);
  chainB->SetBranchStatus("pf_els_dr03TkSumPt",1);
  chainB->SetBranchStatus("pf_els_dr03HcalTowerSumEt",1);
  chainB->SetBranchStatus("pf_els_sigmaIEtaIEta",1);
  chainB->SetBranchStatus("pf_els_dPhiIn",1);
  chainB->SetBranchStatus("pf_els_dEtaIn",1);
  chainB->SetBranchStatus("pf_els_dPhiOut",1);
  chainB->SetBranchStatus("pf_els_dEtaOut",1);
  chainB->SetBranchStatus("pf_els_scEta",1);
  chainB->SetBranchStatus("pf_els_hadOverEm",1);
  chainB->SetBranchStatus("pf_els_isEB",1);
  chainB->SetBranchStatus("pf_els_isEE",1);
  chainB->SetBranchStatus("pf_els_energy",1);
  chainB->SetBranchStatus("pf_els_scEnergy",1);
  chainB->SetBranchStatus("pf_els_scE2x5Max",1);
  chainB->SetBranchStatus("pf_els_scE5x5",1);
  chainB->SetBranchStatus("pf_els_scE1x5",1);
  chainB->SetBranchStatus("pf_els_dr03HcalDepth1TowerSumEt",1);
  chainB->SetBranchStatus("pf_els_dr03HcalDepth2TowerSumEt",1);
  chainB->SetBranchStatus("pf_els_eOverPIn",1);
  chainB->SetBranchStatus("pf_els_numlosthits",1);
  chainB->SetBranchStatus("pf_els_vx",1);
  chainB->SetBranchStatus("pf_els_vy",1);
  chainB->SetBranchStatus("pf_els_vz",1);
  chainB->SetBranchStatus("pf_els_chargedHadronIso",1);
  chainB->SetBranchStatus("pf_els_neutralHadronIso",1);
  chainB->SetBranchStatus("pf_els_photonIso",1);

  chainB->SetBranchStatus("jets_AK5PFclean_rawPt",1);
  chainB->SetBranchStatus("jets_AK5PFclean_et",1);
  chainB->SetBranchStatus("jets_AK5PFclean_btag_TC_highPur",1);
  chainB->SetBranchStatus("jets_AK5PFclean_btag_TC_highEff",1);
  chainB->SetBranchStatus("jets_AK5PFclean_btag_secVertexHighPur",1);
  chainB->SetBranchStatus("jets_AK5PFclean_btag_secVertexHighEff",1);
  chainB->SetBranchStatus("jets_AK5PFclean_btag_secVertexCombined",1);
  chainB->SetBranchStatus("jets_AK5PFclean_btag_jetProb",1);
  chainB->SetBranchStatus("jets_AK5PFclean_btag_jetBProb",1);
  chainB->SetBranchStatus("jets_AK5PFclean_jetCharge",1);
  chainB->SetBranchStatus("jets_AK5PFclean_partonFlavour",1);
  chainB->SetBranchStatus("jets_AK5PFclean_parton_Id",1);
  chainB->SetBranchStatus("jets_AK5PFclean_parton_motherId",1);
  chainB->SetBranchStatus("jets_AK5PFclean_energy",1);
  chainB->SetBranchStatus("jets_AK5PFclean_pt",1);
  chainB->SetBranchStatus("jets_AK5PFclean_px",1);
  chainB->SetBranchStatus("jets_AK5PFclean_py",1);
  chainB->SetBranchStatus("jets_AK5PFclean_gen_pt",1);
  chainB->SetBranchStatus("jets_AK5PFclean_gen_phi",1);
  chainB->SetBranchStatus("jets_AK5PFclean_pz",1);
  chainB->SetBranchStatus("jets_AK5PFclean_eta",1);
  chainB->SetBranchStatus("jets_AK5PFclean_ehf",1);
  chainB->SetBranchStatus("jets_AK5PFclean_phi",1);
  chainB->SetBranchStatus("jets_AK5PFclean_neutralEmE",1);
  chainB->SetBranchStatus("jets_AK5PFclean_chgEmE",1);
  chainB->SetBranchStatus("jets_AK5PFclean_neutralHadE",1);
  chainB->SetBranchStatus("jets_AK5PFclean_chgHadE",1);
  chainB->SetBranchStatus("jets_AK5PFclean_mu_Mult",1);
  chainB->SetBranchStatus("jets_AK5PFclean_neutral_Mult",1);
  chainB->SetBranchStatus("jets_AK5PFclean_chg_Mult",1);
  chainB->SetBranchStatus("jets_AK5PFclean_corrFactorRaw",1);
  chainB->SetBranchStatus("jets_AK5PFclean_photonEnergy",1);

  chainB->SetBranchStatus("jets_AK5PF_et",1);
  chainB->SetBranchStatus("jets_AK5PF_btag_TC_highPur",1);
  chainB->SetBranchStatus("jets_AK5PF_btag_TC_highEff",1);
  chainB->SetBranchStatus("jets_AK5PF_btag_secVertexHighPur",1);
  chainB->SetBranchStatus("jets_AK5PF_btag_secVertexHighEff",1);
  chainB->SetBranchStatus("jets_AK5PF_btag_secVertexCombined",1);
  chainB->SetBranchStatus("jets_AK5PF_btag_jetProb",1);
  chainB->SetBranchStatus("jets_AK5PF_btag_jetBProb",1);
  chainB->SetBranchStatus("jets_AK5PF_jetCharge",1);
  chainB->SetBranchStatus("jets_AK5PF_partonFlavour",1);
  chainB->SetBranchStatus("jets_AK5PF_parton_Id",1);
  chainB->SetBranchStatus("jets_AK5PF_parton_motherId",1);
  chainB->SetBranchStatus("jets_AK5PF_energy",1);
  chainB->SetBranchStatus("jets_AK5PF_pt",1);
  chainB->SetBranchStatus("jets_AK5PF_px",1);
  chainB->SetBranchStatus("jets_AK5PF_py",1);
  chainB->SetBranchStatus("jets_AK5PF_gen_pt",1);
  chainB->SetBranchStatus("jets_AK5PF_gen_phi",1);
  chainB->SetBranchStatus("jets_AK5PF_pz",1);
  chainB->SetBranchStatus("jets_AK5PF_eta",1);
  chainB->SetBranchStatus("jets_AK5PF_ehf",1);
  chainB->SetBranchStatus("jets_AK5PF_phi",1);
  chainB->SetBranchStatus("jets_AK5PF_neutralEmE",1);
  chainB->SetBranchStatus("jets_AK5PF_chgEmE",1);
  chainB->SetBranchStatus("jets_AK5PF_neutralHadE",1);
  chainB->SetBranchStatus("jets_AK5PF_chgHadE",1);
  chainB->SetBranchStatus("jets_AK5PF_mu_Mult",1);
  chainB->SetBranchStatus("jets_AK5PF_neutral_Mult",1);
  chainB->SetBranchStatus("jets_AK5PF_chg_Mult",1);
  chainB->SetBranchStatus("jets_AK5PF_corrFactorRaw",1);
  chainB->SetBranchStatus("jets_AK5PF_photonEnergy",1);	
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT10_px",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT10_py",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT10_pz",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT10_energy",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT10_phi",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT10_eta",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT10_index",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT10_nconstituents",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT15_px",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT15_py",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT15_pz",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT15_energy",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT15_phi",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT15_eta",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT15_index",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT15_nconstituents",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT20_px",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT20_py",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT20_pz",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT20_energy",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT20_phi",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT20_eta",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT20_index",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT20_nconstituents",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT25_px",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT25_py",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT25_pz",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT25_energy",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT25_phi",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT25_eta",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT25_index",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT25_nconstituents",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT30_px",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT30_py",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT30_pz",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT30_energy",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT30_phi",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT30_eta",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT30_index",1);
  chainB->SetBranchStatus("fastjets_AK5PFclean_R1p2_R0p5pT30_nconstituents",1);
  

  chainB->SetBranchStatus("pfmets_et",1);
  chainB->SetBranchStatus("pfmets_ex",1);
  chainB->SetBranchStatus("pfmets_ey",1);
  chainB->SetBranchStatus("pfmets_phi",1);
  chainB->SetBranchStatus("pfmets_sumEt",1);
  chainB->SetBranchStatus("pfmets_gen_et",1);
  chainB->SetBranchStatus("pfmets_gen_phi",1);

  chainB->SetBranchStatus("pfTypeImets_et",1);
  chainB->SetBranchStatus("pfTypeImets_ex",1);
  chainB->SetBranchStatus("pfTypeImets_ey",1);
  chainB->SetBranchStatus("pfTypeImets_phi",1);
  chainB->SetBranchStatus("pfTypeImets_sumEt",1);
  chainB->SetBranchStatus("pfTypeImets_gen_et",1);
  chainB->SetBranchStatus("pfTypeImets_gen_phi",1);

  chainB->SetBranchStatus("pv_x",1);
  chainB->SetBranchStatus("pv_y",1);
  chainB->SetBranchStatus("pv_z",1);
  chainB->SetBranchStatus("pv_tracksSize",1);
  chainB->SetBranchStatus("pv_ndof",1);
  chainB->SetBranchStatus("pv_isFake",1);
  chainB->SetBranchStatus("Npv",1);

  chainB->SetBranchStatus("run",1);
  chainB->SetBranchStatus("event",1);
  chainB->SetBranchStatus("lumiblock",1);
  chainB->SetBranchStatus("bunchCrossing",1);

  chainB->SetBranchStatus("beamSpot_y",1);
  chainB->SetBranchStatus("beamSpot_x",1);

  chainB->SetBranchStatus("weight",1);
  chainB->SetBranchStatus("model_params",1);

  // Make the new file
  TFile *newFile = new TFile(output_filename.Data(),"RECREATE");
  TDirectoryFile *dir = new TDirectoryFile("configurableAnalysis","configurableAnalysis");
  dir->cd();
  TTree *newtreeA = chainA->CloneTree(0);
  TTree *newtreeB = chainB->CloneTree(0);

  Int_t nentries = (Int_t)chainB->GetEntries();

  for (int iEnt = 0; iEnt<nentries; iEnt++) {
    chainA->GetEntry(iEnt);
    chainB->GetEntry(iEnt);
    newtreeA->Fill();
    newtreeB->Fill();
  }

  newtreeA->AutoSave();
  newtreeB->AutoSave();
  newFile->Write();
  newFile->Close();

}
